name: actiontest
on:
  workflow_dispatch:

jobs:
  actiontest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/docker-multi-login
        name: Docker Multi Login