name: ubuntu
on:
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:
    inputs:
      tag:
        description: 'Use this tag instead of most recent'
        required: false
      ignore-existing-tag:
        description: 'Ignore existing tag if "true"'
        required: false
env:
  IMAGES: ${{ github.repository_owner }}/${{ github.workflow }}
  PLATFORMS: "linux/amd64,linux/arm64,linux/arm/v7"
jobs:
  version-check:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.check-tag.outputs.tag }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get Upstream Version
        id: check
        run: |
          if [ -z "${{ github.event.inputs.tag }}" ]
          then
            echo ::set-env name=version::$(curl -s https://registry.hub.docker.com/v1/repositories/library/${{ github.workflow }}/tags | jq -r '.[] | select(.name | contains("focal")) | .name'  | tail -n1)
          fi
      - uses: ./.github/actions/tag-check-action
        name: Check Tag Against DockerHub
        id: check-tag
        with:
          image: library/${{ github.workflow }}
          tag: ${{ github.event.inputs.tag || env.version }}
  multiarch:
    needs: version-check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: ./.github/actions/docker-target-image-list-action
        name: Generate Target Images
        id: gen-tags
        with:
          images: ${{ env.IMAGES }}
          tags: ${{ needs.version-check.outputs.tag }}
      - name: Setup Cache
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          install: true
          version: latest
          driver-opts: image=moby/buildkit:master
      - name: Build and Push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./images/${{ github.workflow }}/Dockerfile
          build-args: VERSION=${{ needs.version-check.outputs.tag }}
          platforms: ${{ env.PLATFORMS }}
          tags: ${{ steps.gen-tags.outputs.fully-qualified-target-images }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
          push: true
      - name: Inspect
        run: |
          IFS=',' read -r -a images <<< "${{ steps.gen-tags.outputs.fully-qualified-target-images }}"
          for image in "${images[@]}"; do
              docker buildx imagetools inspect ${image}
          done
